//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracy.WebFrameworks.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporation
    {
        public Corporation()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public int CorporationID { get; set; }
        public int ParentCorpID { get; set; }
        public string CorporationCode { get; set; }
        public string CorporationName { get; set; }
        public string Address { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
