//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracy.WebFrameworks.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Tracy.WebFrameworks.Entity;
    
    public partial class WebFrameworksDB : DbContext
    {
        public WebFrameworksDB()
            : base(string.Format(@"metadata=res://*/WebFrameworksDB.csdl|res://*/WebFrameworksDB.ssdl|res://*/WebFrameworksDB.msl;provider=System.Data.SqlClient;provider connection string='{0};multipleactiveresultsets=True;App=EntityFramework'",System.Configuration.ConfigurationManager.ConnectionStrings["WebFrameworksDB"].ConnectionString))
        {
    		this.Configuration.ProxyCreationEnabled = false; //默认关闭代理类
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Corporation> Corporation { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<Function> Function { get; set; }
        public DbSet<RoleFunction> RoleFunction { get; set; }
    }
}
