
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using DataAnnotationsExtensions;//http://dataannotationsextensions.org/


namespace Tracy.WebFrameworks.Entity.Metadata
{

/// <summary>
/// 公司 CustomMetadata基類
/// </summary>
[DataContract]
public class CorporationMetadataBase
{


	/// <summary>
    /// 公司ID，主键
	/// </summary>
    [DisplayName("公司ID，主键")]
        [Key]
        [Required]
        [Digits]
        [Max(int.MaxValue)]
        [DataMember]
    public object CorporationID { get; set; }


	/// <summary>
    /// 父公司ID
	/// </summary>
    [DisplayName("父公司ID")]
        [Required]
        [Digits]
        [Max(int.MaxValue)]
        [DataMember]
    public object ParentCorpID { get; set; }


	/// <summary>
    /// 
	/// </summary>
    [StringLength(30)]
        [DataMember]
    public object CorporationCode { get; set; }


	/// <summary>
    /// 
	/// </summary>
    [StringLength(50)]
        [DataMember]
    public object CorporationName { get; set; }


	/// <summary>
    /// 公司地址
	/// </summary>
    [DisplayName("公司地址")]
        [StringLength(200)]
        [DataMember]
    public object Address { get; set; }


	/// <summary>
    /// 
	/// </summary>
    [Required]
        [StringLength(30)]
        [DataMember]
    public object CreatedBy { get; set; }


	/// <summary>
    /// 创建时间
	/// </summary>
    [DisplayName("创建时间")]
        [Required]
        [DataType(DataType.Date)]
        [UIHint("DatePicker")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [DataMember]
    public object CreatedTime { get; set; }


	/// <summary>
    /// 最近修改人
	/// </summary>
    [DisplayName("最近修改人")]
        [StringLength(30)]
        [DataMember]
    public object LastUpdateBy { get; set; }


	/// <summary>
    /// 最近修改时间
	/// </summary>
    [DisplayName("最近修改时间")]
        [DataType(DataType.Date)]
        [UIHint("DatePicker")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [DataMember]
    public object LastUpdateTime { get; set; }

}


}
