
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using DataAnnotationsExtensions;//http://dataannotationsextensions.org/


namespace Tracy.WebFrameworks.Entity.Metadata
{

/// <summary>
/// 职员(用户)，一个用户只属于一个公司的一个部门。 CustomMetadata基類
/// </summary>
[DataContract]
public class EmployeeMetadataBase
{


	/// <summary>
    /// 
	/// </summary>
    [Key]
    [Required]
    [Digits]
    [Max(int.MaxValue)]
    [DataMember]
    public object EmployeeID { get; set; }


	/// <summary>
    /// 
	/// </summary>
    [Required]
    [Digits]
    [Max(int.MaxValue)]
    [DataMember]
    public object CorporationID { get; set; }


	/// <summary>
    /// 
	/// </summary>
    [Required]
    [Digits]
    [Max(int.MaxValue)]
    [DataMember]
    public object DepartmentID { get; set; }


	/// <summary>
    /// 职员所拥有角色列表，用','分隔
	/// </summary>
    [DisplayName("职员所拥有角色列表，用','分隔")]
    [DataMember]
    public object RoleIDs { get; set; }


	/// <summary>
    /// 
	/// </summary>
    [StringLength(30)]
    [DataMember]
    public object EmployeeName { get; set; }


	/// <summary>
    /// 登录帐号
	/// </summary>
    [DisplayName("登录帐号")]
    [Required]
    [StringLength(30)]
    [DataMember]
    public object LoginName { get; set; }


	/// <summary>
    /// 登录密码，加密保存
	/// </summary>
    [DisplayName("登录密码，加密保存")]
    [Required]
    [StringLength(30)]
    [DataMember]
    public object Password { get; set; }


	/// <summary>
    /// 
	/// </summary>
    [Required]
    [DataType(DataType.Date)]
    [UIHint("DatePicker")]
    [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
    [DataMember]
    public object PwdExpiredTime { get; set; }


	/// <summary>
    /// 性别，0：未知，1：女，2：男
	/// </summary>
    [DisplayName("性别，0：未知，1：女，2：男")]
    [Required]
    [Digits]
    [Max(byte.MaxValue)]
    [DataMember]
    public object Sex { get; set; }


	/// <summary>
    /// 电话
	/// </summary>
    [DisplayName("电话")]
    [StringLength(30)]
    [DataMember]
    public object Phone { get; set; }


	/// <summary>
    /// 邮箱
	/// </summary>
    [DisplayName("邮箱")]
    [StringLength(30)]
    [DataMember]
    public object Email { get; set; }


	/// <summary>
    /// 状态。
	/// </summary>
    [DisplayName("状态。")]
    [Required]
    [Digits]
    [Max(byte.MaxValue)]
    [DataMember]
    public object Status { get; set; }


	/// <summary>
    /// 登录次数
	/// </summary>
    [DisplayName("登录次数")]
    [Digits]
    [Max(int.MaxValue)]
    [DataMember]
    public object LoginCount { get; set; }


	/// <summary>
    /// 最后登录时间
	/// </summary>
    [DisplayName("最后登录时间")]
    [DataType(DataType.Date)]
    [UIHint("DatePicker")]
    [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
    [DataMember]
    public object LastLoginTime { get; set; }


	/// <summary>
    /// 最后登录IP
	/// </summary>
    [DisplayName("最后登录IP")]
    [StringLength(30)]
    [DataMember]
    public object LastLoginIP { get; set; }


	/// <summary>
    /// 
	/// </summary>
    [Required]
    [StringLength(30)]
    [DataMember]
    public object CreatedBy { get; set; }


	/// <summary>
    /// 
	/// </summary>
    [Required]
    [DataType(DataType.Date)]
    [UIHint("DatePicker")]
    [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
    [DataMember]
    public object CreatedTime { get; set; }


	/// <summary>
    /// 
	/// </summary>
    [StringLength(30)]
    [DataMember]
    public object LastUpdateBy { get; set; }


	/// <summary>
    /// 
	/// </summary>
    [DataType(DataType.Date)]
    [UIHint("DatePicker")]
    [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
    [DataMember]
    public object LastUpdateTime { get; set; }

}


}
