
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Tracy.WebFrameworks.Entity.Metadata;


namespace Tracy.WebFrameworks.Entity
{

/// <summary>
/// <para>【WebFrameworks.Entity.tt生成的，与数据库对应的】</para>
/// 公司

/// </summary>
[Serializable]
[DataContract(IsReference = true)]
[MetadataType(typeof(CorporationMetadata))]
public partial class Corporation
{

	/// <summary>
	/// 创建公司新实例
	/// </summary>
    public Corporation()
    {

        this.Department = new HashSet<Department>();

        this.Employee = new HashSet<Employee>();

    }



	/// <summary>
    /// 獲取或設置公司ID，主键
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public int CorporationID { get; set; }


	/// <summary>
    /// 獲取或設置父公司ID
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public int ParentCorpID { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string CorporationCode { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string CorporationName { get; set; }


	/// <summary>
    /// 獲取或設置公司地址
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string Address { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string CreatedBy { get; set; }


	/// <summary>
    /// 獲取或設置创建时间
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public System.DateTime CreatedTime { get; set; }


	/// <summary>
    /// 獲取或設置最近修改人
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string LastUpdateBy { get; set; }


	/// <summary>
    /// 獲取或設置最近修改时间
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public Nullable<System.DateTime> LastUpdateTime { get; set; }




	/// <summary>
    /// 獲取或設置(導航屬性)
	/// </summary>
    [DataMember]
    public virtual ICollection<Department> Department { get; set; }


	/// <summary>
    /// 獲取或設置(導航屬性)
	/// </summary>
    [DataMember]
    public virtual ICollection<Employee> Employee { get; set; }

}


}
