//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracy.WebFrameworks.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public int CorporationID { get; set; }
        public int DepartmentID { get; set; }
        public string RoleIDs { get; set; }
        public string EmployeeName { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public System.DateTime PwdExpiredTime { get; set; }
        public byte Sex { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public byte Status { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string LastLoginIP { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual Corporation Corporation { get; set; }
        public virtual Department Department { get; set; }
    }
}
