
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Tracy.WebFrameworks.Entity.Metadata;


namespace Tracy.WebFrameworks.Entity
{

/// <summary>
/// <para>【WebFrameworks.Entity.tt生成的，与数据库对应的】</para>
/// 

/// </summary>
[Serializable]
[DataContract(IsReference = true)]
[MetadataType(typeof(EmployeeMetadata))]
public partial class Employee
{


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public int EmployeeID { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public Nullable<int> CorporationID { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public Nullable<int> DepartmentID { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string RoleIDs { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string EmployeeName { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string LoginName { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string Password { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public System.DateTime PwdExpiredTime { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public byte Sex { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string Phone { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string Email { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public byte Status { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public int LoginCount { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public Nullable<System.DateTime> LastLoginTime { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string LastLoginIP { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public Nullable<bool> Enabled { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string CreatedBy { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public System.DateTime CreatedTime { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string LastUpdatedBy { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public Nullable<System.DateTime> LastUpdatedTime { get; set; }




	/// <summary>
    /// 獲取或設置(導航屬性)
	/// </summary>
    [DataMember]
    public virtual Corporation Corporation { get; set; }


	/// <summary>
    /// 獲取或設置(導航屬性)
	/// </summary>
    [DataMember]
    public virtual Department Department { get; set; }

}


}
