
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Tracy.WebFrameworks.Entity.Metadata;


namespace Tracy.WebFrameworks.Entity
{

/// <summary>
/// <para>【WebFrameworks.Entity.tt生成的，与数据库对应的】</para>
/// 

/// </summary>
[Serializable]
[DataContract(IsReference = true)]
[MetadataType(typeof(MenuButtonMetadata))]
public partial class MenuButton
{


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public int Id { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public int MenuId { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public int ButtonId { get; set; }




	/// <summary>
    /// 獲取或設置(導航屬性)
	/// </summary>
    [DataMember]
    public virtual Menu Menu { get; set; }


	/// <summary>
    /// 獲取或設置(導航屬性)
	/// </summary>
    [DataMember]
    public virtual Button Button { get; set; }

}


}
