//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracy.WebFrameworks.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.RoleFunction = new HashSet<RoleFunction>();
        }
    
        public int MenuID { get; set; }
        public int ParentMenuID { get; set; }
        public string MenuName { get; set; }
        public string MenuUrl { get; set; }
        public Nullable<int> MenuLevel { get; set; }
        public int SortOrder { get; set; }
        public string MenuIcon { get; set; }
        public Nullable<bool> IsShortcut { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public string FunctionIDs { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual ICollection<RoleFunction> RoleFunction { get; set; }
    }
}
