
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Tracy.WebFrameworks.Entity.Metadata;


namespace Tracy.WebFrameworks.Entity
{

/// <summary>
/// <para>【WebFrameworks.Entity.tt生成的，与数据库对应的】</para>
/// 菜单(页面)

/// </summary>
[Serializable]
[DataContract(IsReference = true)]
[MetadataType(typeof(MenuMetadata))]
public partial class Menu
{

	/// <summary>
	/// 创建菜单(页面)新实例
	/// </summary>
    public Menu()
    {

        this.RoleFunction = new HashSet<RoleFunction>();

    }



	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public int MenuID { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public int ParentMenuID { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string MenuName { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string MenuUrl { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public Nullable<int> MenuLevel { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public int SortOrder { get; set; }


	/// <summary>
    /// 獲取或設置菜单图标url
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string MenuIcon { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public Nullable<bool> IsShortcut { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public Nullable<bool> IsShow { get; set; }


	/// <summary>
    /// 獲取或設置该菜单所包含的操作集合
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string FunctionIDs { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string CreatedBy { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public System.DateTime CreatedTime { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public string LastUpdateBy { get; set; }


	/// <summary>
    /// 獲取或設置
	/// </summary>
    [DatabaseTableColumn]
    [DataMember]
    public Nullable<System.DateTime> LastUpdateTime { get; set; }




	/// <summary>
    /// 獲取或設置(導航屬性)
	/// </summary>
    [DataMember]
    public virtual ICollection<RoleFunction> RoleFunction { get; set; }

}


}
